-- MySQL Script generated by MySQL Workbench
-- Sun Jun  7 14:01:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aliment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aliment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aliment` DEFAULT CHARACTER SET utf8 ;
USE `aliment` ;

-- -----------------------------------------------------
-- Table `aliment`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aliment`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `brand` VARCHAR(50) NULL,
  `store` VARCHAR(50) NULL,
  `country` TEXT NULL,
  `quantity` TEXT NULL,
  `nutriscore` CHAR(1) NULL,
  `url` TEXT NULL,
  `category` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `aliment`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aliment`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `aliment`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aliment`.`product_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_category` INT UNSIGNED NOT NULL,
  `id_product` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_category`
    FOREIGN KEY (`id`)
    REFERENCES `aliment`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `aliment`.`save_food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aliment`.`save_food` (
  `id` INT UNSIGNED NOT NULL,
  `name` TEXT NULL,
  `brand` VARCHAR(50) NULL,
  `store` VARCHAR(50) NULL,
  `country` TEXT NULL,
  `quantity` TEXT NULL,
  `nutriscore` CHAR(1) NULL,
  `url` TEXT NULL,
  `category` VARCHAR(20) NULL,
  `id_product` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_procuct`
    FOREIGN KEY (`id`)
    REFERENCES `aliment`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

CREATE USER 'client' IDENTIFIED BY 'Tkoacote77570+';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
